version: '3.8'

services:
  master:
    image: 'postgres:16.4'
    environment:
      - POSTGRES_DB=socialnetwork
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5431:5432'
    volumes:
      - "./volumes/pgmaster/:/var/lib/postgresql/data"
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


  slave1:
    container_name: "pgslave1"
    image: 'postgres:16.4'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "127.0.0.1:5433:5433"
    volumes:
      - "./volumes/pgslave1/:/var/lib/postgresql/data"

  slave2:
    container_name: "pgslave2"
    image: 'postgres:16.4'
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5434:5434"
    volumes:
      - "./volumes/pgslave2/:/var/lib/postgresql/data"
  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    environment:
      - REDIS_USER=user
      - REDIS_PASSWORD=password


  socialnetwork:
    build: .
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "8080:8080"


