spring:
  docker:
    compose:
      enabled: false
  application:
    name: socialnetwork
  datasource:
    url: jdbc:postgresql://localhost:5431/socialnetwork
    username: postgres
    password: postgres
  jackson:
    default-property-inclusion: non_null

  rabbitmq:
    username: guest
    password: guest
    port: 5672
    virtual-host: /
    host: localhost


server:
  port: 8081



