
spring:
  application:
    name: socialnetwork

  datasource:
    url: jdbc:postgresql://localhost:5431/socialnetwork?currentSchema=socialnetwork
    username: postgres
    password: postgres

  jackson:
    default-property-inclusion: non_null

